### ISSUE TITLE
会删除个人发表的微博吗？

### ISSUE THREAD

**Issue by WonderLand33** [Neulana/Xweibo#1]

**Comment by WonderLand33** [comment]
贴一下报错信息：

```
➜  Xweibo git:(master) ✗ python3 src/del.py
Traceback (most recent call last):
  File "src/del.py", line 14, in <module>
    weibo.login(WEIBO_USERNAME, WEIBO_PASSWORD)
  File "/Users/champion/test/Xweibo/src/weibo.py", line 46, in login
    s_user_name = self.get_username()
  File "/Users/champion/test/Xweibo/src/weibo.py", line 110, in get_username
    username_quote = urllib.parse.quote_plus(self.user_name)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 807, in quote_plus
    string = quote(string, safe + space, encoding, errors)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 791, in quote
    return quote_from_bytes(string, safe)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/parse.py", line 816, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

**Comment by pinple** [comment]
@champion97 抱歉，现在才看到这个issue（github的提醒机制有点弱啊）
你输入的WEIBO_USERNAME是微博昵称还是用于登录的邮箱？报的是编码错误，我猜测你输入到是昵称，是中文，所以报错了。我在README里写了，这里应该是填写登录时用的账号，例如邮箱、手机号等，**_而不是微博昵称_**。在这里上确实有点误导用户了。
